### ISSUE TITLE
How Pods can be killed once they finish the build process?

### ISSUE THREAD

**Issue by cdsap** [cdsap/Bagan#10]
Currently, the execution of the Pod is happening on the `poststart` step of the life cycle of the pod. 

```
apiVersion: v1
kind: Pod
metadata:
  name: experiment1
  labels:
    app: experiment
    type: experiment
    experimentid: QleQWn6CsB1gxQveUUpa
  annotations:
    seccomp.security.alpha.kubernetes.io/pod: 'docker/default'
spec:
  initContainers:
    - name: git-clone
      image: alpine/git
      args:
        - clone
        - --single-branch
        - --
        - {{ .Values.repository }}
        - /repo
      securityContext:
        runAsUser: 1
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
      volumeMounts:
        - name: git-repo
          mountPath: /repo
  containers:
    - name:  agent
      image: {{ .Values.image }}
      args: ['sleep', '100000']
      envFrom:
        - configMapRef:
            name: {{ .Values.configMaps }}
      volumeMounts:
        - name: git-repo
          mountPath: /repo
      lifecycle:
            postStart:
              exec:
                command:
                - bash
                - -c
                - |
                  mv *.kt /repo
                  cd /repo
                  source /usr/share/sdkman/bin/sdkman-init.sh
                  source /root/.bashrc
                  kscript TalaiotInjector.kt
                  kscript RewriteProperties.kt
                  for i in `seq 1 {{ .Values.iterations }}`; do {{ .Values.command }}; done
  volumes:
    - name: git-repo
      emptyDir: {}
```

Anton has suggested the Pod has to be killed by himself once is finished, I need some support here
